before_install:
 - yes | sdkmanager "platforms;android-28"
 - mkdir -p "$ANDROID_HOME/licenses"
 - echo -e "\nd56f5187479451eabf01fb78af6dfcb131a6481e\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
 - chmod +x gradlew

language: android
jdk:
  - oraclejdk8
android:
  components:
    - tools
    - build-tools-28.0.2
    - android-28
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository

  licenses:
    - 'android-sdk-license-.+'
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - platform-tools
    # - tools

    # The BuildTools version used by your project
    #- build-tools-23.0.2

    # The SDK version used to compile your project
    #- android-23

    # Additional components
    #- extra-google-google_play_services
    #- extra-google-m2repository
    #- extra-android-m2repository
    #- addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    #- sys-img-armeabi-v7a-android-19
    #- sys-img-x86-android-17

script: ./gradlew build check
